import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Beranda from "./Beranda";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white flex h-screen`}
      >
          <Beranda/>
        <div className=" flex-1 overflow-y-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
